---
- name: Write etcd config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf

- name: Write etcd systemd unit file for Debian
  copy: src=etcd.service dest=/etc/systemd/system
  notify:
    - reload systemd
  when: ansible_distribution == "Debian"

- name : Setting the etcd_modified fact to true  
  set_fact:
    etcd_modified: true
